# Configuration file for Active Learning experiments

experiments:
  - name: Random
    embeddings_dir: ESC10_BASEAL/embeddings/birdnet/
    annotations_path: ESC10_BASEAL/labels.csv
    model_name: birdnet
    hidden_dim: null
    sampling_strategy: random
    learning_rate: 0.001
    repeats: 1
    device: cpu
    pretrain_samples: null

  - name: Margin
    embeddings_dir: ESC10_BASEAL/embeddings/birdnet/
    annotations_path: ESC10_BASEAL/labels.csv
    model_name: birdnet
    hidden_dim: null
    sampling_strategy: sklearn_margin_multilabel
    learning_rate: 0.001
    repeats: 1
    device: cpu
    pretrain_samples: null

  # - name: CoreSet
  #   embeddings_dir: ATBFL_BASEAL_Data/embeddings/perch_v2/
  #   annotations_path: ATBFL_BASEAL_Data/labels.csv
  #   model_name: perch_v2
  #   hidden_dim: null
  #   sampling_strategy: sklearn_coreset
  #   learning_rate: 0.001
  #   repeats: 1
  #   device: cpu
  #   pretrain_samples: null

  # - name: TypiCluster
  #   embeddings_dir: ATBFL_BASEAL_Data/embeddings/perch_v2/
  #   annotations_path: ATBFL_BASEAL_Data/labels.csv
  #   model_name: perch_v2
  #   hidden_dim: null
  #   sampling_strategy: sklearn_typiclust
  #   learning_rate: 0.001
  #   repeats: 1
  #   device: cpu
  #   pretrain_samples: null
